package seedu.address.model.person;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static seedu.address.testutil.Assert.assertThrows;

import org.junit.jupiter.api.Test;

public class DetailsTest {

    @Test
    public void constructor_null_throwsNullPointerException() {
        assertThrows(NullPointerException.class, () -> new Details(null));
    }

    @Test
    public void constructor_whitespaceDetails_success() {
        // Whitespace-only details should succeed because constructor trims to empty string
        Details details = new Details("   ");
        assertEquals("", details.value);
    }

    @Test
    public void isValidDetails() {
        // null details
        assertThrows(NullPointerException.class, () -> Details.isValidDetails(null));

        // blank details
        assertTrue(Details.isValidDetails("")); // empty string is valid (no details)
        assertFalse(Details.isValidDetails(" ")); // spaces only

        // valid details, Generated by AI
        assertTrue(Details.isValidDetails("Loves coffee and morning runs"));
        assertTrue(Details.isValidDetails("First-time home buyer looking for 3-bedroom HDB"));
        assertTrue(Details.isValidDetails("Property investor with 5 years experience"));
        assertTrue(Details.isValidDetails("Prefers fully furnished units near MRT"));
        assertTrue(Details.isValidDetails("!@#$%^&*()_+")); // special characters allowed
        assertTrue(Details.isValidDetails("A")); // single character
        assertTrue(Details.isValidDetails(createStringWithLength(512))); // exactly 512 characters
        assertTrue(Details.isValidDetails("This is a valid details string that should be accepted"
                + " as long as it's within the 512 character limit"));

        // test bounds
        assertFalse(Details.isValidDetails(createStringWithLength(513))); // more than 512 characters
    }

    @Test
    public void constructor() {
        // Test valid details constructor
        Details details = new Details("Sample details");
        assertTrue(details.value.equals("Sample details"));
    }

    @Test
    public void equals() {
        Details details = new Details("Test details");

        // same values -> returns true
        assertTrue(details.equals(new Details("Test details")));

        // same object -> returns true
        assertTrue(details.equals(details));

        // null -> returns false
        assertFalse(details.equals(null));

        // different types -> returns false
        assertFalse(details.equals(5.0f));
        assertFalse(details.equals("string"));
        assertFalse(details.equals(new Object()));

        // different values -> returns false
        assertFalse(details.equals(new Details("Different details")));
    }

    @Test
    public void hashCode_consistent() {
        Details details = new Details("Test details");
        int firstHash = details.hashCode();
        int secondHash = details.hashCode();
        assertEquals(firstHash, secondHash);
    }

    @Test
    public void toString_returnsValue() {
        Details details = new Details("Test details");
        assertEquals("Test details", details.toString());
    }

    /**
     * Creates a string with the specified length consisting of 'a' characters.
     */
    private String createStringWithLength(int length) {
        return "a".repeat(length);
    }
}
