@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Details
Person *--> "0..1" Meeting

Meeting : -dateTime: LocalDateTime
Meeting : +getDateTime(): LocalDateTime
Meeting : +getFormattedDateTime(): String
Meeting : +getCommandFormat(): String
Meeting : DISPLAY_FORMATTER: DateTimeFormatter\n("dd MMM yyyy h:mm am/pm")
@enduml
