@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "f:FavouritesCommand" as FavouritesCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":FilteredList<Person>" as FilteredList MODEL_COLOR
end box

[-> LogicManager : execute("favourites")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("favourites")
activate AddressBookParser

create FavouritesCommand
AddressBookParser -> FavouritesCommand
activate FavouritesCommand

FavouritesCommand --> AddressBookParser
deactivate FavouritesCommand

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FavouritesCommand : execute(Model)
activate FavouritesCommand

FavouritesCommand -> Model : updateFilteredPersonList(person -> person.getIsFavourite())
activate Model

Model -> FilteredList : setPredicate(predicate)
activate FilteredList

note right of FilteredList
  Predicate filters persons where
  **isFavourite == true**

  Only persons marked as favourites
  will be shown in the list
end note

FilteredList --> Model
deactivate FilteredList

Model --> FavouritesCommand
deactivate Model

create CommandResult
FavouritesCommand -> CommandResult : new CommandResult("Listed all favourite persons")
activate CommandResult

CommandResult --> FavouritesCommand
deactivate CommandResult

FavouritesCommand --> LogicManager : r
deactivate FavouritesCommand

[<--LogicManager : r
deactivate LogicManager

@enduml
